[dependencies]
base = "0.9.1"
vector = "0.1.2"
prng = "0.0.1"
enumeration = "0.0.1"
mrr = "https://github.com/research-ag/motoko-lib"
wip = "https://github.com/research-ag/motoko-wip#main"
motoko-sha2 = "https://github.com/timohanke/motoko-sha2#v2.0.0"
"crypto.mo" = "https://github.com/skilesare/crypto.mo#main"
zhus = "https://github.com/ZhenyaUsenko/motoko-hash-map#master"
motoko-hash-map = "https://github.com/ZhenyaUsenko/motoko-hash-map#v7.0.0"