[dependencies]
vector = "0.2.0"
prng = "0.0.3"
enumeration = "0.1.0"
sha2 = "0.0.4"
wip = "https://github.com/research-ag/motoko-wip#main"
motoko-sha2 = "https://github.com/timohanke/motoko-sha2#v2.0.0"
"crypto.mo" = "https://github.com/skilesare/crypto.mo#main"
zhus = "https://github.com/ZhenyaUsenko/motoko-hash-map#master"
hpl = "../hpl"

base = "0.10.3"
swb = "1.1.0"
promtracker = "https://github.com/research-ag/promtracker#eabe0aa0303781a0f398bb9bcd1e537b59ab24e9"
mrr = "https://github.com/research-ag/motoko-lib#bc0a2ba3e529ab3ff38ce20fbbc2e4c23ebb4ee7"
stable_enumeration = "https://github.com/research-ag/stable_enumeration#fdac6535144dede29d4edcfe778cbb8e40bf1897"
btree = "https://github.com/research-ag/MotokoStableBTree"
streams = "https://github.com/research-ag/streams#99b2b38a3002e90d5a5cd36df4d5f2a815964822@99b2b38a3002e90d5a5cd36df4d5f2a815964822"
