[dependencies]
base = "https://github.com/dfinity/motoko-base#6bea744"
vector = "0.1.2"
prng = "0.0.1"
enumeration = "https://github.com/research-ag/enumeration#bump-0.9.2"
mrr = "https://github.com/research-ag/motoko-lib"
wip = "https://github.com/research-ag/motoko-wip#main"
motoko-sha2 = "https://github.com/timohanke/motoko-sha2#v2.0.0"
"crypto.mo" = "https://github.com/skilesare/crypto.mo#main"
zhus = "https://github.com/ZhenyaUsenko/motoko-hash-map#master"
