[dependencies]
base = "0.10.1"
vector = "0.2.0"
prng = "0.0.3"
enumeration = "0.1.0"
sha2 = "0.0.4"
mrr = "https://github.com/research-ag/motoko-lib#ec8c5364ce08d11aa6e99583deb7fe5825debd16"
wip = "https://github.com/research-ag/motoko-wip#main"
motoko-sha2 = "https://github.com/timohanke/motoko-sha2#v2.0.0"
"crypto.mo" = "https://github.com/skilesare/crypto.mo#main"
zhus = "https://github.com/ZhenyaUsenko/motoko-hash-map#master"
stable_enumeration = "https://github.com/research-ag/stable_enumeration"
btree = "https://github.com/research-ag/MotokoStableBTree#main"
