[dependencies]
base = "0.10.4"
vector = "0.2.0"
prng = "0.0.3"
enumeration = "0.1.0"
sha2 = "0.0.4"
stable-trie = "https://github.com/research-ag/stable-trie#deeaee3c0b34ffffe238d238bb7bd2bc30794960"
mrr = "https://github.com/research-ag/motoko-lib#9939f9e79ce37e975b64aec18c0f9b186514bdaf"
wip = "https://github.com/research-ag/motoko-wip#main"
motoko-sha2 = "https://github.com/timohanke/motoko-sha2#v2.0.0"
"crypto.mo" = "https://github.com/skilesare/crypto.mo#main"
zhus = "https://github.com/ZhenyaUsenko/motoko-hash-map#master"
stable_enumeration = "https://github.com/research-ag/stable_enumeration"
btree = "https://github.com/research-ag/MotokoStableBTree#main"

[toolchain]
moc = "0.10.4"
